/*jslint node: true */

'use strict';

const replace = require('replace-in-file');
// https://www.npmjs.com/package/replace-in-file


var fromList = [
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Central &amp; Arctic:CAR - RDG Central &amp; Arctic::Electronics and Informatics/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Maritimes::CAR - Habitat/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Maritimes:MAR - Canadien Coast Guard::E&amp;I - Electronics and Informatics/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Maritimes:MAR - Canadien Coast Guard::ME - Marine Engineering/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Maritimes:MAR - Canadien Coast Guard::Strategic Business Management/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Maritimes:MAR - Oceans and Habitat::MAR - Regional Director/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:::Atlantic/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:::NCR - Business and Resource Management/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:::NCR - Policies and Practices/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:::NCR - Treaty Policy &amp; Negotiations, Aboriginal Affairs/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::CAR - CCG, Integrated Technical Services/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::Communications/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::Corporate Services Delivery Unit/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::HR Strategies - HR Operations and Systems/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::Human Resources/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::Human Resources:Organizational Performance and Executive Services/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::Inf. Mgmnt &amp; Tech Svcs/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::Int`l Affairs/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::Integrated Business Management/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::Integrated Technical Services/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::National Strategies/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::NCR - Ecosystem Science/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::Real Property Safety and Security/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::Special Projects/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:Human Resources and Corporate Services::Business Management, Integration and Engagement/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:Human Resources and Corporate Services::Events and Outreach/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - Aquatic Ecosystems::Atlantic/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - Aquatic Ecosystems::Integrated Program Planning &amp; Analysis/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - Aquatic Ecosystems::NCR - Policies and Practices/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - Ecosystems and Oceans Science::NCR - Aquaculture, Biotechnology and Aquatic Animal Health Science/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - Ecosystems and Oceans Science::NCR - Oceans Management/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - Fisheries Harbour Management::NCR - Treaty Policy &amp; Negotiations, Aboriginal Affairs/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - Fisheries Harbour Management::Pacific, Arctic and Inland/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - International Affairs::NCR - Global Trade and Market Access Bureau/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - International Affairs::NCR - Office of the Associate Director General/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - International Affairs::NCR - Strategic Planning/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - International Affairs::NCR - Strategic Policy/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - International Affairs::NCR - US and Asia\/Pacific Regional Affairs Bureau/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - Strategic Policy::NCR - Horizontal Policies and Priorities/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - Strategic Policy::NCR - International Fisheries Commissions/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - Strategic Policy::NCR - Strategic Policy/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:Policy::NCR - Horizontal Policies and Priorities/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:Policy::NCR - Science Policy and Strategy/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:Policy::NCR - Strategic Planning/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:Policy::NCR - Strategic Priorities/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:Science::NCR - Aquaculture, Biotechnology and Aquatic Animal Health Science/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Newfoundland \/ Labrador:NCR - Strategic Policy::NCR - International Fisheries Commissions/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Newfoundland \/ Labrador:NFL - Canadian Coast Guard::Electronics and Informatics/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Newfoundland \/ Labrador:NFL - Canadian Coast Guard::MCI - Maritime and Civil Infrastructure/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Quebec::QUE - Aquaculture/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Quebec:QUE - Information Management and Tech. Services::QUE - Information Technology service center/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:::Solutions Development and Integration/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:::NCR - Global Trade and Market Access Bureau/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - Strategic Policy::NCR - Horizontal Priorities/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::NCR - Legislative and Intergovernmental Affairs/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:::NCR - Global Marine and Northern Affairs Bureau/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Maritimes::Inf. Mgmnt &amp; Tech Svcs/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - International Affairs::NCR - Global Marine and Northern Affairs Bureau/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region::NCR Operations/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:NCR - Aquatic Ecosystems::NCR - Office of the Associate Director General/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):::National Strategies:Preparedness and Response/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Pacific::Science and Oceans/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):::NCR - Ecosystem Science/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Quebec::QUE - Info. Management &amp; Tech. Servi./g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):Newfoundland \/ Labrador:NFL - Canadian Coast Guard::Atlantic/g,
    /DFO\/CCG - GCDOCS:Legacy\(EKME\):National Capital Region:Human Resources and Corporate Services::Organizational Performance and Executive Services/g
];

var toList = ["DFO/CCG - GCDOCS:Legacy(EKME):Central &amp; Arctic:CAR - RDG Central &amp; Arctic:Electronics and Informatics",
    "DFO/CCG - GCDOCS:Legacy(EKME):Maritimes:CAR - Habitat",
    "DFO/CCG - GCDOCS:Legacy(EKME):Maritimes:MAR - Canadien Coast Guard:E&amp;I - Electronics and Informatics",
    "DFO/CCG - GCDOCS:Legacy(EKME):Maritimes:MAR - Canadien Coast Guard:ME - Marine Engineering",
    "DFO/CCG - GCDOCS:Legacy(EKME):Maritimes:MAR - Canadien Coast Guard:Strategic Business Management",
    "DFO/CCG - GCDOCS:Legacy(EKME):Maritimes:MAR - Oceans and Habitat:MAR - Regional Director",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Program Policy:Atlantic",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Business and Resource Management",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Oceans:Habitat Mgmt:NCR - Policies and Practices",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Program Policy:ZZ_NCR - Fisheries and Aboriginal Policy:NCR - Treaty Policy &amp; Negotiations, Aboriginal Affairs",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:CAR - CCG, Integrated Technical Services",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Communications:Communications",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Human Ressources:Corporate Services Delivery Unit",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Human Ressources:HR Strategies - HR Operations and Systems",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Human Resources and Corporate Services:Human Resources",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Human Ressources:Human Resources:Organizational Performance and Executive Services",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Human Ressources:Inf. Mgmnt &amp; Tech Svcs",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Fisheries and Aquaculture Management:Int`l Affairs",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Fisheries and Aquaculture Management:Integrated Business Management",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Integrated Technical Services",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Fisheries and Aquaculture Management:National Strategies",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Oceans:NCR - Ecosystem Science",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Infrastructure &amp; Information Management:Real Property Safety and Security",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Special Projects",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Human Resources and Corporate Services:Business Management, Integration and Engagement",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Human Resources and Corporate Services:Events and Outreach",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Aquatic Ecosystems:Atlantic",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Aquatic Ecosystems:Integrated Program Planning &amp; Analysis",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Aquatic Ecosystems:NCR - Policies and Practices",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Ecosystems and Oceans Science:NCR - Aquaculture, Biotechnology and Aquatic Animal Health Science",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Ecosystems and Oceans Science:ZZ_NCR - Oceans:NCR - Oceans Management",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Fisheries Harbour Management:ZZ_NCR - Fisheries and Aboriginal Policy:NCR - Treaty Policy &amp; Negotiations, Aboriginal Affairs",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Fisheries Harbour Management:ZZ_NCR - Aquaculture Management:Pacific, Arctic and Inland",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - International Affairs:NCR - Global Trade and Market Access Bureau",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - International Affairs:NCR - Office of the Associate Director General",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - International Affairs:NCR - Strategic Planning",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - International Affairs:NCR - Strategic Policy",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - International Affairs:NCR - US and Asia/Pacific Regional Affairs Bureau",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Strategic Policy:NCR - Horizontal Policies and Priorities",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Strategic Policy:NCR - International Fisheries Commissions",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Strategic Policy:NCR - Strategic Policy",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Policy:NCR - Horizontal Policies and Priorities",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Policy:NCR - Science Policy and Strategy",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Policy:NCR - Strategic Planning",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Policy:NCR - Strategic Priorities",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Science:NCR - Aquaculture, Biotechnology and Aquatic Animal Health Science",
    "DFO/CCG - GCDOCS:Legacy(EKME):Newfoundland / Labrador:NCR - Strategic Policy:NCR - International Fisheries Commissions",
    "DFO/CCG - GCDOCS:Legacy(EKME):Newfoundland / Labrador:NFL - Canadian Coast Guard:Electronics and Informatics",
    "DFO/CCG - GCDOCS:Legacy(EKME):Newfoundland / Labrador:NFL - Canadian Coast Guard:MCI - Maritime and Civil Infrastructure",
    "DFO/CCG - GCDOCS:Legacy(EKME):Quebec:QUE - Fisheries and Aquaculture:QUE - Aquaculture",
    "DFO/CCG - GCDOCS:Legacy(EKME):Quebec:QUE - Information Management and Tech. Services:QUE - Information Technology service center",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Solutions Development and Integration",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Global Trade and Market Access Bureau",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Strategic Policy:NCR - Horizontal Priorities",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Legislative and Intergovernmental Affairs",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Global Marine and Northern Affairs Bureau",
    "DFO/CCG - GCDOCS:Legacy(EKME):Maritimes:Inf. Mgmnt &amp; Tech Svcs",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - International Affairs:NCR - Global Marine and Northern Affairs Bureau",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR Operations",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:NCR - Aquatic Ecosystems:NCR - Office of the Associate Director General",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Strategies:Preparedness and Response",
    "DFO/CCG - GCDOCS:Legacy(EKME):Pacific:Science and Oceans",
    "DFO/CCG - GCDOCS:Legacy(EKME):NCR - Ecosystem Science",
    "DFO/CCG - GCDOCS:Legacy(EKME):Quebec:QUE - Info. Management &amp; Tech. Servi.",
    "DFO/CCG - GCDOCS:Legacy(EKME):Newfoundland / Labrador:NFL - Canadian Coast Guard:Atlantic",
    "DFO/CCG - GCDOCS:Legacy(EKME):National Capital Region:Human Resources and Corporate Services:Organizational Performance and Executive Services"
];
const options = {
    files: [
        './destination/oiEKME_2014-05-30_001.xml',
        './destination/oiEKME_2014-11-30_001.xml'
    ],
    from: fromList,
    to: toList,
    countMatches: true,
    dry: false, // use true to actually replace the string(s) in the file(s)
};

try {
    const results = replace.sync(options);
    console.log('Replacement results:', results);
} catch (error) {
    console.error('Error occurred:', error);
}